### ISSUE TITLE
test 4 - Malofeiev Denys AI-201

### ISSUE THREAD

**Issue by Dekshut** [oleksandrblazhko/ai201-malofeev#19]
1.

CREATE TABLE users(
	...,
	email VARCHAR CHECK(email ~* '^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$'),
	mobile VARCHAR CHECK (mobile ~* '^\+?3?8?(0[\s\.-]\d{2}[\s\.-]\d{3}[\s\.-]\d{2}[\s\.-]\d{2})$')
);

2. ![image](https://github.com/oleksandrblazhko/ai201-malofeev/blob/ai201-malofeev_with_laboratory_work_6/2-SoftwareDesign/2.5-UMLProgramClasses/UML-ProgramClasses.jpg?raw=true)

Authority: до цього класу додали унікальний id та зв'язок з классом Roles через Set<Role>
Roles: до цього класу додали унікальний id та зв'язок з классом Authority через Set<Authority>
User: до цього класу додали унікальний id та зв'язок з классом Sculpture через Set<Sculpture>
Sculpture: 
-до цього класу додали унікальний id та зв'язок з классом User через Set<User>
-до цього класу додали унікальний тип SculptureType и зв'язок з класом SculptureType
Material: до цього класу додали унікальний id та зв'язок з классом Sculpture через Set<Sculpture>

**Comment by oleksandrblazhko** [comment]
Перше рішення не відповідає завданню, бо треба було створити новий вираз.
Оцінка = 2 бали.
