### ISSUE TITLE
CW2

### ISSUE THREAD

**Issue by Dekshut** [oleksandrblazhko/ai201-malofeev#7]

**Comment by Dekshut** [comment]
Завдання 1
Атомарність ПП надає список регіонів, інформацію про вологість, а також рекомендації щодо живописних місць
Завершеність Користувач обирає
Безкоштовність Користувач натискає кнопку формуючи Online-замовлення
Завдання 2
Розподілена система 2
Через спеціификацію обраного середовища розробки ПП нам ніяких зайвих технологій не потрібно, корім БД, тому проект досить легкий
Спеціальні вимоги до навчання користувачів 1
В ПП продукті є лише два активних користувача Живописець та Агент недвижимости
Через розподілення функціоналу продукту та його загальну спрощеність від користувачів потребується мінімальний досвід

**Comment by oleksandrblazhko** [comment]
Коментарі до рішення 1-го завдання:
1) умова "атомарність" порушується, якщо описано декілька дій зразу
2) умова "завершеність" порушується, якщо немає формату Subject-Action-Object
3) "безкоштовніть реалізації" порушується, якщо, наприклад, 
використовуються графічний інтерфейс
У вас не всі завдання виконано правильно.

Оцінка = 2 бали
